// Picks the 50 levels from the solved candidates in tools/out and writes game/levels.js.
// node tools/build-levels.js
// Each world gets 10 levels, sorted easier to harder, and each world starts around the
// middle of the previous world's difficulty so the game keeps getting harder overall.
const fs = require('fs');
const path = require('path');

const PER_WORLD = 10;

const NAMES = [
  ['First Drop', 'Hot Seat', 'Cool Head', 'Steam Room', 'Simmer Down', 'Lava Lamp', 'Dry Run', 'Fizzle', 'Boiling Point', 'Meltdown'],
  ['Rock Bottom', 'Pebble Path', 'Stone Wall', 'Gravel Pit', 'Rockslide', 'Heavy Load', 'Sink Hole', 'Boulder Dash', 'Rubble Trouble', 'Landslide'],
  ['Jammed', 'Stuck Fast', 'Key Hole', 'Gridlock', 'Chain Reaction', 'Lock Down', 'Tight Spot', 'Domino', 'Deadbolt', 'Lockpick'],
  ['Double Trouble', 'Split Decision', 'Twin Flames', 'Fair Share', 'Two Timer', 'Divide', 'Pair of Fires', 'Spread Thin', 'Fork in the Road', 'Double Down'],
  ['Cold Snap', 'Brain Freeze', 'Ice Breaker', 'Thaw', 'Frostbite', 'Snow Melt', 'Glacier', 'Cold Feet', 'Avalanche', 'Final Freeze'],
];

const HINTS = [
  'Water puts out fire. Lava makes it bigger. Water turns lava into stone.',
  'New: rocks! They sink through water and lava, and they can fill a drain.',
  'New: locked pins. Rock jamming a handle stops the pin. Clear it first!',
  'New: two fires. Both must go out, so share your water.',
  'New: ice. It is frozen water. A touch of lava melts the whole block.',
];

function load(world) {
  const f = path.join(__dirname, 'out', `world${world}.jsonl`);
  if (!fs.existsSync(f)) return [];
  const seen = new Set();
  const out = [];
  for (const line of fs.readFileSync(f, 'utf8').split('\n')) {
    if (!line.trim()) continue;
    const c = JSON.parse(line);
    if (seen.has(c.seed)) continue;
    seen.add(c.seed);
    out.push(c);
  }
  return out.sort((a, b) => a.score - b.score);
}

function signature(c) {
  const l = c.level;
  return [l.route.join('/'), l.pins.length, l.fills.map((f) => f.t[0]).sort().join('')].join('|');
}

// Choose n candidates spread over [lo, hi] of the score range, avoiding repeated layouts.
function spread(pool, n, lo) {
  const usable = pool.filter((c) => c.score >= lo);
  const src = usable.length >= n ? usable : pool.slice(-Math.max(n, usable.length));
  const picked = [];
  const sigs = new Set();
  for (let k = 0; k < n; k++) {
    const q = n === 1 ? 1 : k / (n - 1);
    let idx = Math.round(q * (src.length - 1));
    // walk outwards from the target until we find a fresh layout
    let best = null;
    for (let d = 0; d < src.length && !best; d++) {
      for (const j of [idx + d, idx - d]) {
        const c = src[j];
        if (c && !picked.includes(c) && !sigs.has(signature(c))) { best = c; break; }
      }
    }
    if (!best) best = src.find((c) => !picked.includes(c));
    if (!best) break;
    picked.push(best);
    sigs.add(signature(best));
  }
  return picked.sort((a, b) => a.score - b.score);
}

const levels = [];
const report = [];
let prevMid = 0;
for (let w = 1; w <= 5; w++) {
  const pool = load(w);
  if (!pool.length) { console.log(`world ${w}: no candidates yet`); continue; }
  const chosen = spread(pool, PER_WORLD, prevMid);
  prevMid = chosen[Math.floor(chosen.length / 2)] ? chosen[Math.floor(chosen.length / 2)].score : prevMid;
  chosen.forEach((c, k) => {
    const lv = c.level;
    const out = {
      name: NAMES[w - 1][k] || `World ${w}-${k + 1}`,
      seed: lv.seed,
      need: lv.need,
      walls: lv.walls,
      lines: lv.lines,
      pins: lv.pins,
      fills: lv.fills,
      fires: lv.fires,
      drains: lv.drains,
    };
    if (k === 0) out.hint = HINTS[w - 1];
    if (levels.length === 0) out.tutorialPin = c.best[0];
    for (const key of Object.keys(out)) if (out[key] === undefined) delete out[key];
    levels.push(out);
    report.push({ level: levels.length, world: w, name: out.name, seed: c.seed, score: c.score, minSteps: c.minSteps, winRate: Math.round(c.winRate * 1000) / 1000, pins: c.pins, solution: c.best });
  });
  console.log(`world ${w}: ${pool.length} candidates, picked ${chosen.length}, scores ${chosen.map((c) => c.score).join(' ')}`);
}

const js = `// Flame Out - the 50 levels. Generated by tools/build-levels.js from solver-checked candidates.
// Do not edit by hand; regenerate instead. Every player gets exactly these levels.
(function (root) {
  'use strict';
  const LEVELS = ${JSON.stringify(levels)};
  const api = { LEVELS };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else root.FlameLevels = api;
})(typeof window !== 'undefined' ? window : globalThis);
`;
fs.writeFileSync(path.join(__dirname, '..', 'game', 'levels.js'), js);
fs.writeFileSync(path.join(__dirname, 'levels-report.json'), JSON.stringify(report, null, 1));
console.log(`wrote ${levels.length} levels`);
