// Scripted plays: [step, pinId]. Every level needs a winning line and its traps must lose.
module.exports = [
  { level: 1, label: 'pull the only pin', plan: [[0, 0]], expect: 'won' },
  { level: 2, label: 'water pin', plan: [[0, 0]], expect: 'won' },
  { level: 2, label: 'lava pin', plan: [[0, 1]], expect: 'lost', reason: 'lava' },
  { level: 3, label: 'water, wait, floor', plan: [[0, 0], [500, 1]], expect: 'won' },
  { level: 3, label: 'floor first', plan: [[0, 1]], expect: 'lost', reason: 'lava' },
  { level: 3, label: 'floor too soon', plan: [[0, 0], [20, 1]], expect: 'lost' },
  { level: 4, label: 'water then right door', plan: [[0, 0], [150, 2]], expect: 'won' },
  { level: 4, label: 'right door then water', plan: [[0, 2], [10, 0]], expect: 'won' },
  { level: 4, label: 'water then left door', plan: [[0, 0], [150, 1]], expect: 'lost', reason: 'water' },
  { level: 4, label: 'lava tank', plan: [[0, 3]], expect: 'lost', reason: 'lava' },
  { level: 5, label: 'both waters, wait, floor', plan: [[0, 0], [0, 1], [700, 3]], expect: 'won' },
  { level: 5, label: 'one water then floor', plan: [[0, 0], [600, 3]], expect: 'lost', reason: 'lava' },
  { level: 5, label: 'decoy lava added', plan: [[0, 0], [0, 1], [0, 2], [900, 3]], expect: 'lost' },
  { level: 5, label: 'floor first', plan: [[0, 3]], expect: 'lost', reason: 'lava' },
  { level: 6, label: 'rocks then water', plan: [[0, 1], [200, 0]], expect: 'won' },
  { level: 6, label: 'water first', plan: [[0, 0]], expect: 'lost', reason: 'water' },
  { level: 7, label: 'rocks, water, wait, floor', plan: [[0, 1], [200, 0], [900, 2]], expect: 'won' },
  { level: 7, label: 'water first', plan: [[0, 0]], expect: 'lost', reason: 'water' },
  { level: 7, label: 'floor first', plan: [[0, 2]], expect: 'lost', reason: 'lava' },
  { level: 7, label: 'floor too soon', plan: [[0, 1], [200, 0], [300, 2]], expect: 'lost' },
  { level: 8, label: 'rocks', plan: [[0, 0]], expect: 'won' },
  { level: 8, label: 'lava tank', plan: [[0, 1]], expect: 'lost', reason: 'lava' },
  { level: 9, label: 'water, wait, rocks', plan: [[0, 0], [700, 1]], expect: 'won' },
  { level: 9, label: 'rocks first', plan: [[0, 1]], expect: 'lost', reason: 'lava' },
  { level: 10, label: 'rocks, water, wait, floor', plan: [[0, 1], [200, 0], [900, 3]], expect: 'won' },
  { level: 10, label: 'decoy lava, then the right line', plan: [[0, 2], [0, 1], [200, 0], [900, 3]], expect: 'lost' },
  { level: 10, label: 'water first', plan: [[0, 0]], expect: 'lost', reason: 'water' },
  { level: 10, label: 'floor first', plan: [[0, 3]], expect: 'lost', reason: 'lava' },
];
